# Generated by Django 2.1.5 on 2021-02-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210216_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/avatars/avatar_default.png', null=True, upload_to='avatars/', verbose_name='Аватар пользователя'),
        ),
    ]
