# Generated by Django 2.1.5 on 2021-02-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/avatars/avatar_default.png', upload_to='avatars/', verbose_name='Аватар пользователя'),
        ),
    ]
