# Generated by Django 2.1.5 on 2021-02-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_referal_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referal_link',
            field=models.CharField(default='None', max_length=200, unique=True, verbose_name='Реферальная ссылка'),
        ),
    ]
