# Generated by Django 2.1.5 on 2021-02-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20210217_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='referal1_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referal2_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referal3_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referal4_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='referal1_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во рефералов в первой линии'),
        ),
        migrations.AddField(
            model_name='profile',
            name='referal2_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во рефералов во второй линии'),
        ),
        migrations.AddField(
            model_name='profile',
            name='referal3_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во рефералов в третьей линии'),
        ),
        migrations.AddField(
            model_name='profile',
            name='referal4_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во рефералов в четвертой линии'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sponsor_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Уникальный номер спонсора'),
        ),
    ]
