# Generated by Django 2.1.5 on 2021-02-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_referal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referal',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Referal',
        ),
    ]
