# Generated by Django 2.1.5 on 2021-02-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20210218_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('ru', 'ru'), ('en', 'en'), ('es', 'es')], default='ru', max_length=200, verbose_name='Язык пользователя'),
        ),
    ]
