# Generated by Django 2.1.5 on 2021-02-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='None', max_length=200, verbose_name='Страна пользователя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ip',
            field=models.CharField(default='None', max_length=200, verbose_name='IP пользователя'),
        ),
    ]
