# Generated by Django 2.1.5 on 2021-02-24 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_auto_20210219_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 19, 45, 39, 177274), verbose_name='Дата и время регистрации'),
        ),
    ]
