# Generated by Django 2.1.5 on 2021-04-28 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_auto_20210428_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 28, 15, 4, 1, 375693), verbose_name='Дата и время регистрации'),
        ),
    ]
