# Generated by Django 2.1.5 on 2021-04-29 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_auto_20210428_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 13, 9, 13, 781270), verbose_name='Дата и время регистрации'),
        ),
    ]
