# Generated by Django 2.1.5 on 2021-04-29 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_auto_20210429_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.CharField(default='0', max_length=200, unique=True, verbose_name='Уникальный номер'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 13, 27, 39, 708045), verbose_name='Дата и время регистрации'),
        ),
    ]
