# Generated by Django 2.1.5 on 2021-04-29 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_auto_20210429_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 17, 1, 36, 406937), verbose_name='Дата и время регистрации'),
        ),
    ]
