# Generated by Django 2.1.5 on 2021-05-02 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_auto_20210502_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 17, 27, 11, 932800), verbose_name='Дата и время регистрации'),
        ),
    ]
