# Generated by Django 2.1.5 on 2021-05-03 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0036_auto_20210502_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 12, 22, 50, 292354), verbose_name='Дата и время регистрации'),
        ),
    ]
