# Generated by Django 2.1.5 on 2021-05-03 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0038_auto_20210503_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 12, 47, 20, 85472), verbose_name='Дата и время регистрации'),
        ),
    ]
