# Generated by Django 2.1.5 on 2021-05-03 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0039_auto_20210503_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 12, 57, 34, 670882), verbose_name='Дата и время регистрации'),
        ),
    ]
