# Generated by Django 2.1.5 on 2021-05-15 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0042_auto_20210506_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 15, 18, 41, 52, 627943), verbose_name='Дата и время регистрации'),
        ),
    ]
