# Generated by Django 2.1.5 on 2021-05-15 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0043_auto_20210515_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 15, 19, 33, 3, 969231), verbose_name='Дата и время регистрации'),
        ),
    ]
