# Generated by Django 2.1.5 on 2021-05-31 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0044_auto_20210515_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 20, 22, 13, 530296), verbose_name='Дата и время регистрации'),
        ),
    ]
