# Generated by Django 2.1.5 on 2021-04-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_profilerequest_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilerequest',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Тема'),
        ),
    ]
