# Generated by Django 2.1.5 on 2021-02-22 13:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название банка')),
                ('country', models.CharField(max_length=200, verbose_name='Страна банка')),
                ('offer_id', models.CharField(max_length=200, verbose_name='ID оффера в лидгиде')),
                ('description', models.TextField(verbose_name='Описание банка')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='banks/', verbose_name='Логотип банка')),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None, verbose_name='Категории')),
                ('link', models.CharField(max_length=200, verbose_name='Ссылка на банк')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
            },
        ),
    ]
