# Generated by Django 2.1.5 on 2021-04-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Номер приоритета в списке категории'),
        ),
        migrations.AddField(
            model_name='bank',
            name='number_all',
            field=models.IntegerField(default=1, verbose_name='Номер приоритета в общем списке'),
        ),
    ]
