# Generated by Django 2.1.5 on 2021-04-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_bank_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='categories',
        ),
        migrations.AddField(
            model_name='bank',
            name='category',
            field=models.CharField(choices=[('Займы', 'Займы'), ('Кредиты', 'Кредиты'), ('Кредитные карты', 'Кредитные карты'), ('Дебитовые карты', 'Дебитовые карты'), ('РКО', 'РКО'), ('Залоги', 'Залоги'), ('Ипотека', 'Ипотека'), ('Рефинансирование', 'Рефинансирование'), ('Для бизнеса', 'Для бизнеса')], default='Займы', max_length=200, verbose_name='Вид кредитования'),
        ),
    ]
