# Generated by Django 2.1.5 on 2021-04-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0006_auto_20210429_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='rate',
            field=models.CharField(default='1 % в день', max_length=200, verbose_name='Ставка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='summ',
            field=models.CharField(default='до 30 000 руб. ', max_length=200, verbose_name='Сумма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='term',
            field=models.CharField(default='до 30 дней ', max_length=200, verbose_name='Срок'),
            preserve_default=False,
        ),
    ]
