# Generated by Django 2.1.5 on 2021-05-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0007_auto_20210429_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='summ',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='term',
        ),
        migrations.AddField(
            model_name='bank',
            name='line1',
            field=models.CharField(default='Сумма:\nдо 30 000 руб.', max_length=200, verbose_name='Строка 1'),
        ),
        migrations.AddField(
            model_name='bank',
            name='line2',
            field=models.CharField(default='Ставка:\n1 % в день', max_length=200, verbose_name='Строка 2'),
        ),
        migrations.AddField(
            model_name='bank',
            name='line3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Строка 4'),
        ),
    ]
