# Generated by Django 2.1.5 on 2021-05-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0008_auto_20210502_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='line1',
            field=models.CharField(max_length=200, verbose_name='Строка 1'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='line2',
            field=models.CharField(max_length=200, verbose_name='Строка 2'),
        ),
    ]
