# Generated by Django 2.1.5 on 2021-05-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0009_auto_20210502_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='line4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Строка 4'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='line3',
            field=models.CharField(default='Срок:\nдо 30 дней', max_length=200, verbose_name='Строка 3'),
            preserve_default=False,
        ),
    ]
