# Generated by Django 2.1.5 on 2021-05-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0010_auto_20210502_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='product_photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото продукта'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='line1',
            field=models.TextField(verbose_name='Строка 1'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='line2',
            field=models.TextField(verbose_name='Строка 2'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='line3',
            field=models.TextField(verbose_name='Строка 3'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='line4',
            field=models.TextField(blank=True, null=True, verbose_name='Строка 4'),
        ),
    ]
