# Generated by Django 2.1.5 on 2021-05-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0011_auto_20210503_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='frame',
            field=models.CharField(choices=[('Нет', 0), ('Зеленая', 1), ('Красная', 2), ('Синяя', 3)], default=0, max_length=200, verbose_name='Рамка'),
        ),
    ]
