# Generated by Django 2.1.5 on 2021-05-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0013_auto_20210503_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='frame',
            field=models.CharField(choices=[('Нет', 'Нет'), ('Зеленая', 'Зеленая'), ('Красная', 'Красная'), ('Синяя', 'Синяя')], default='Нет', max_length=200, verbose_name='Рамка'),
        ),
    ]
